//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class example {
  public static int add(int a, int b) {
    int ret = examplePINVOKE.add(a, b);
    return ret;
  }

  public static int subtract(int b, int c) {
    int ret = examplePINVOKE.subtract(b, c);
    return ret;
  }

}
